# Generated by Django 4.2.5 on 2023-09-14 13:06

import app_instagram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=350)),
                ('path', models.ImageField(upload_to=app_instagram.models.update_filename)),
            ],
        ),
    ]
